server:
  port: 8763
spring:
  application:
    name: shuibeizi-sys-write
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shuibeizi?useUnicode=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      idle-timeout: 3500000
      max-lifetime: 21600000
      data-source-properties:
        cache-prep-stmts: true
        use-server-prep-stmts: true
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
mybatis:
  type-aliases-package: com.shuibeizi.sys.dao
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    region: shuibeizi
    availability-zones:
      shuibeizi: loc,dev
    service-url:
      loc: http://127.0.0.1:8761/eureka
      dev: http://116.62.159.166:8761/eureka
  instance:
    prefer-ip-address: true
    appname: shuibeizi-sys-write

logging:
  config: classpath:log4j2.xml

